# Generated by Django 4.2.2 on 2023-06-24 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_productpropertymodel_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=200)),
                ('propType', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.customer')),
            ],
        ),
    ]
