# Generated by Django 4.2.2 on 2023-06-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_product_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='buildyear',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
