# Generated by Django 4.2.2 on 2023-06-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_feature_buildyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='imageone',
            field=models.ImageField(default='images/default_image.jpg', upload_to='apartmentImage/'),
        ),
        migrations.AddField(
            model_name='feature',
            name='imagethree',
            field=models.ImageField(default='images/default_image.jpg', upload_to='apartmentImage/'),
        ),
        migrations.AddField(
            model_name='feature',
            name='imagetwo',
            field=models.ImageField(default='images/default_image.jpg', upload_to='apartmentImage/'),
        ),
    ]
